<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sizzle.Application\Sizzle.Application.csproj" />
    <ProjectReference Include="..\Sizzle.Infrastructure\Sizzle.Infrastructure.csproj" />
    <ProjectReference Include="..\Sizzle.Domain\Sizzle.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Requests\Ingredients\" />
  </ItemGroup>

</Project>
